FROM node:22.6.0-alpine3.20 AS base

# 1. Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app
COPY ../src/package.json ./
RUN npm install

# 2. Rebuild the source code only when needed
FROM base AS builder
RUN apk add --no-cache dumb-init
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY ./src .
COPY  docker/env/.env.production .env
RUN npm run build

# 3. Production image, copy all the files and run next
FROM base AS runner
WORKDIR /usr/src/app

ENV NODE_ENV=production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /usr/src/app/public ./public

COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/static ./.next/static
COPY --from=builder /usr/bin/dumb-init /usr/bin/dumb-init


USER nextjs

EXPOSE 80

ENV PORT=80

# CMD HOSTNAME=localhost node index.js
CMD ["dumb-init", "node", "server.js"]